### ISSUE TITLE
Expose a way to configure Llama to use less memory

### ISSUE THREAD

**Issue by haldunanil** [poyro/poyro#22]
node llama provides a variety of parameters that control the configuration of how models are run by llama cpp. These are exposed as parameters of the different core objects in node llama: `LlamaContext`, `LlamaModel`, and `LlamaChatSession`. We may want to expose these as a single configuration that gets passed to `getModel` to configure things so that the end user can control them from a single configuration class. See this [Perplexity](https://www.perplexity.ai/search/In-node-llama-UepJrK1XTquv2c10Q08suw) response for some details. 

For more information it's best to consult the [llama-cli docs](https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md#performance-tuning-and-memory-options) which contain the full set of parameters that could be configured. Many of the properties there are exposed in node llama through the classes listed above.

FYI @haldunanil

**Comment by dabs9** [comment]
Closing, moved to Trello.
